export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
export const CHANGE_TYPE = "CHANGE_TYPE";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_SCORE = "CHANGE_SCORE";
export const CHANGE_USERNAME = "CHANGE_USERNAME";
// export const FETCH_DATA = "FETCH_DATA";
export const CHANGE_PLAYERS = "CHANGE_PLAYERS";
export const CHANGE_PLAYER = "CHANGE_PLAYER";

